services:
  api:
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app

  postgresql:
    ports:
      - ${DB_PORT}:5432

  ngrok:
    restart: unless-stopped
    command: http api:8000 --scheme http,https
    ports:
      - 4040:4040
